apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  annotations:
    secret.reloader.stakater.com/reload: "secret"
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: cloudflared
  template:
    metadata:
      labels:
        pod: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: "cloudflare/cloudflared:2023.10.0"
          imagePullPolicy: IfNotPresent
          command:
            - cloudflared
            - tunnel
            - --no-autoupdate
            - --metrics
            - 0.0.0.0:2000
            - run
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: tunnelToken
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
