apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: ollama
  labels:
    app.kubernetes.io/crds: enabled
    app.kubernetes.io/remediation: enabled
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: ollama
      version: 1.4.1
      sourceRef:
        kind: HelmRepository
        name: ollama
  # https://github.com/otwld/ollama-helm/blob/main/values.yaml
  values:
    persistentVolume:
      enabled: true
      size: ${ollama_persistent_volume_size:=3Gi}
