apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: homelab-local
volumes:
  - volume: k3d-homelab-local-storage:/var/lib/rancher/k3s/storage
network: k3d-homelab-local
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
      - arg: "--disable=metrics-server"
        nodeFilters:
          - server:*
registries:
  config: |
    mirrors:
      "docker.io":
        endpoint:
          - http://host.k3d.internal:5001
      "registry.k8s.io":
        endpoint:
          - http://host.k3d.internal:5002
      "gcr.io":
        endpoint:
          - http://host.k3d.internal:5003
      "ghcr.io":
        endpoint:
          - http://host.k3d.internal:5004
      "quay.io":
        endpoint:
          - http://host.k3d.internal:5005
      "mcr.microsoft.com":
        endpoint:
          - http://host.k3d.internal:5006
