apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8sgpt-operator
  namespace: k8sgpt-operator
  labels:
    helm.toolkit.fluxcd.io/crds: enabled
    helm.toolkit.fluxcd.io/helm-test: enabled
    helm.toolkit.fluxcd.io/remediation: enabled
spec:
  interval: 10m
  chart:
    spec:
      chart: k8sgpt-operator
      version: 0.2.6
      sourceRef:
        kind: HelmRepository
        name: k8sgpt-operator
  # https://github.com/k8sgpt-ai/k8sgpt-operator/blob/main/chart/operator/values.yaml
  values: {}
