apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 5m
  dependsOn:
    - name: traefik
      namespace: traefik
    - name: cert-manager
      namespace: cert-manager
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: harbor
      version: 1.13.1
      sourceRef:
        kind: HelmRepository
        name: harbor
  # https://github.com/goharbor/harbor-helm/blob/main/values.yaml
  values:
    externalURL: https://harbor.${cluster_domain}${harbor_port:=} # harbor_port is necessary for the ingress route to work with non-default https ports (e.g. :8443 in docker)
    expose:
      tls:
        certSource: none
      ingress:
        hosts:
          core: harbor.${cluster_domain}
