apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
  labels:
    helm.toolkit.fluxcd.io/crds: enabled
    helm.toolkit.fluxcd.io/helm-test: enabled
    helm.toolkit.fluxcd.io/remediation: enabled
spec:
  interval: 10m
  chart:
    spec:
      chart: homepage
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: homepage
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: homepage
            patch: |
              - op: add
                path: /metadata/annotations/configmap.reloader.stakater.com~1reload
                value: homepage
  # ICONS:
  # https://github.com/walkxcode/dashboard-icons
  # https://simpleicons.org
  # https://pictogrammers.com/library/mdi/
  # ---
  # https://github.com/jameswynn/helm-charts/blob/main/charts/homepage/values.yaml
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v0.10.9
    enableRbac: true
    serviceaccount:
      create: true
    ingress:
      main:
        enabled: true
        hosts:
          - host: homepage.${cluster_domain}
            paths:
              - path: /
                pathType: Prefix
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
    config:
      kubernetes:
        mode: cluster
      settings:
        title: Homelab
        favicon: https://devantler.com/assets/images/author.png
        theme: dark
        color: slate
        background:
          image: https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
          blur: sm
          opacity: 70
        providers:
          longhorn:
            url: http://longhorn-frontend.longhorn-system:80
      widgets:
        - logo:
            icon: https://devantler.com/assets/images/author.png
        - greeting:
            text_size: xl
            text: Welcome to Devantler's Homelab! 🚀
        - search:
            provider: google
            target: _blank
        - datetime:
            text_size: xl
            format:
              dateStyle: long
              timeStyle: short
              hourCycle: h23
        - openmeteo:
            units: metric
            cache: 5
        - resources:
            backend: kubernetes
            expanded: true
            cpu: true
            memory: true
        - longhorn:
            expanded: true
            total: true
            labels: false
            nodes: false
      services:
        - Network:
            - Cloudflare:
                icon: cloudflare
                href: https://cloudflare.${cluster_domain}
                description: Central hub for managing public networking, e.g. FQDN, DNS and remote tunneling.
                widget:
                  type: cloudflared
                  accountid: 634e9016d402443e427865dc35457728
                  tunnelid: 3284a342-3b0f-4530-a60e-07338e2bec17
                  key: ${cloudflared_tunnel_api_token}
            - UniFi:
                icon: unifi
                href: https://unifi.ui.com
                description: Central hub for managing on-prem UniFi network infrastructure.
        - Monitoring:
            - Grafana:
                icon: grafana
                href: https://devantler.grafana.net
                description: Central hub for monitoring my infrastructure.
        - Virtualization Platforms:
            - Hetzner Cloud:
                icon: hetzner
                href: https://console.hetzner.cloud/projects
                description: Cloud infrastructure provider.
        - Cluster Provisioning:
            - Omni:
                icon: si-talos-#FF7300
                href: https://omni.${cluster_domain}
                description: Platform for provisioning and managing Talos Linux clusters.
        - Analytics:
            - Disqus:
                icon: si-disqus-#2E9FFF
                href: https://disqus.com
                description: Platform to track and moderate embedded comments on my sites.
            - Google Analytics:
                icon: google-analytics
                href: https://analytics.google.com
                description: Web analytics service.
      bookmarks:
        - Personal:
            - GitHub Pages:
                - icon: github-light
                  href: https://${cluster_domain}
        - Dev:
            - GitHub:
                - icon: github-light
                  href: https://github.com
            - NuGet:
                - icon: si-nuget-#1088d6
                  href: https://www.nuget.org
            - Codecov:
                - icon: si-codecov-#F01F7A
                  href: https://app.codecov.io
            - Renovate:
                - icon: si-renovatebot-#007fa0
                  href: https://developer.mend.io
        - Ops:
            - ArtifactHUB:
                - icon: si-artifacthub-#417598
                  href: https://artifacthub.io
            - CRD Docs:
                - icon: si-kubernetes-#326CE5
                  href: https://doc.crds.dev
            - Network Policy Editor:
                - icon: si-kubernetes-#326CE5
                  href: https://editor.networkpolicy.io
