apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: goldilocks
  labels:
    helm.toolkit.fluxcd.io/crds: enabled
    helm.toolkit.fluxcd.io/helm-test: enabled
    helm.toolkit.fluxcd.io/remediation: enabled
spec:
  interval: 10m
  chart:
    spec:
      chart: goldilocks
      version: 9.0.1
      sourceRef:
        kind: HelmRepository
        name: goldilocks
  # https://github.com/FairwindsOps/charts/blob/master/stable/goldilocks/values.yaml
  values:
    dashboard:
      ingress:
        enabled: true
        ingressClassName: ${ingress_class_name:=}
        hosts:
          - host: goldilocks.${cluster_domain}
            paths:
              - path: /
                type: ImplementationSpecific
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Goldilocks
          gethomepage.dev/description: Dashboard for automated vertical pod autoscaling recommendations.
          gethomepage.dev/group: Management
          gethomepage.dev/icon: mdi-white-balance-sunny-#FFA500
          gethomepage.dev/app: goldilocks-dashboard
          gethomepage.dev/pod-selector: app.kubernetes.io/name=goldilocks
