name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    uses: devantler-tech/actions/.github/workflows/create-release.yaml@a147ead8b8bc937fbfb1974e3698c7e32f95517d # v13.5.1
    with:
      disable-issue-side-effects: true
    permissions:
      contents: write # create releases and tags
      id-token: write # provenance signing
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
