name: Sync Cluster Policies

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "k8s/bases/infrastructure/cluster-policies/samples/**"

permissions: {}

jobs:
  sync-policies:
    uses: devantler-tech/actions/.github/workflows/sync-cluster-policies.yaml@883d891a0e6a2c9420d2b60aea9d5f47c20ce803 # v13.5.0
    with:
      kyverno-policies-dir: k8s/bases/infrastructure/cluster-policies/samples
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
