name: Sync Cluster Policies

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "k8s/bases/infrastructure/cluster-policies/samples/**"

permissions: {}

jobs:
  sync-policies:
    uses: devantler-tech/actions/.github/workflows/sync-cluster-policies.yaml@a147ead8b8bc937fbfb1974e3698c7e32f95517d # v13.5.1
    with:
      kyverno-policies-dir: k8s/bases/infrastructure/cluster-policies/samples
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
