name: "TODOs"
on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  issues: write

jobs:
  todos:
    uses: devantler-tech/actions/.github/workflows/scan-for-todo-comments.yaml@883d891a0e6a2c9420d2b60aea9d5f47c20ce803 # v13.5.0
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
